name: release-updates
on:
  release:
    types:
      - published
permissions:
  contents: write

jobs:
  checksum_file:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare
        shell: bash
        run: |
          echo "SERVER_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.SERVER_VERSION }}"

      - name: Post release updates
        shell: bash
        env:
          UPLOAD_CHECKSUM: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scripts/ci/post_release_updates.sh

      - name: Commit post release updates changes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Jose Quintana'
          git config --global user.email '1700322+joseluisq@users.noreply.github.com'
          git add scripts/installer.sh docs/content/download-and-install.md docs/content/download-and-install.template.md
          git commit -m "docs: ${{ env.SERVER_VERSION }} [skip ci]"
          git push
